### ISSUE TITLE
Possible API error/change

### ISSUE THREAD

**Issue by TheGrayGoblin** [tehmufifnman/tsm_imports#2]
The import list has started acting strangely for me since Tuesday, August 15th.  Various items are no longer showing up as being in their appropriate groups, are not grouped at all, or (for example) i860s are showing as i810.  Apologies if this is not the proper place to report this issue.

**Comment by tehmufifnman** [comment]
There was TSM addon update I deployed last night for bonus ids.  I have not had a chance to update my groups yet.  Stay tuned. :)
