### ISSUE TITLE
Invalid Item Hyperlink/ 0 items successfully imported

### ISSUE THREAD

**Issue by TheGrayGoblin** [tehmufifnman/tsm_imports#3]
Importing the larger new item lists (e.g. "Leg_Arm_Clo_Epic.txt") from raw results in an "invalid item hyperlink" LUA error in TSM.  Importing smaller, subdivided lists (e.g. Leg_Arm_Clo_Epic_101_Avd.txt) from raw results in "successfully imported 0 new items" in TSM.  All of my addons are up to date through TSMApplication premium.  If you need to know anything else, I'm happy to provide more information.  As an aside, thank you so much for compiling/posting all of these lists.  :)

**Comment by tehmufifnman** [comment]
Should be fixed!  I had a typo in my group creation (was missing a colon)
