### ISSUE TITLE
Missing TSM Import Groups for Legion 

### ISSUE THREAD

**Issue by Gunnydelight** [tehmufifnman/tsm_imports#7]
You had a complete list of TSM legion groups but I dont see that here, nor in sub folders

**Comment by tehmufifnman** [comment]
I only maintain xpac specific groups for the currect xpac, since thats
the only xpac where ultra specific versions matter (wf/socket, etc),
and people dont want the item just for xmog.

Legion items are in the General groups, and if not let me know.

**Comment by Gunnydelight** [comment]
TY for the quick response!

**Comment by Gunnydelight** [comment]
Hey @tehmufifnman 

I went through the directories, didn't see a general directory that this was listed under. Can you post the repo/dir it is under?

**Comment by tehmufifnman** [comment]
There won't be an explicit directory for old xpacs.  The items will just be
in their general armor/weapon type folders.

**Comment by Gunnydelight** [comment]
alright, gracias senior!
